### ISSUE TITLE
compile fpga host code error 

### ISSUE THREAD

**Issue by mohmsslk** [Atrifex/Code-Acceleration#1]
Hello, 
First thank you for this projetc, I was trying to compile the host code in the part fpgaOpenCL_implementation and I get this error : 'hdf5/include/hdf5.h no such file or directory' in line 30 of cnn.h, and this for windows 8.1 and CentOS 6.x,
Do you have a solution dor that ?
Thank you

**Comment by atrifex** [comment]
Thanks :) I am glad that you like it.

Since the FPGA implementation can't use the Hunter package manager, the best way to use HDF5 is to download the tools and install them locally.

When I was writing this code, the problem was that I did not have root access to the system that I was working on. Due to this, I had to download a portable version of the library and access the lib files directly in the make files. You can do this as well. However, I recommend just installing the library so that you can continue to use it for other projects.

**Comment by atrifex** [comment]
I am going to close this issue for now. Please do feel free to reopen it if you have more questions.

**Comment by mohmsslk** [comment]
I have another problem, what you did about szip ? I install it but not working, if you disable it how you did it ?
